//
//  Recipe.swift
//  RecipeApp
//
//  Created by Talha Asif on 02/10/2021.
//

import Foundation

enum Category:String,Identifiable,CaseIterable{
    
    var id:String{self.rawValue}
    
    case breakfast = "Breakfast"
    case soup = "Soup"
    case salad = "Salad"
    case appetizer = "Appetizer"
    case main = "Main"
    case side = "Side"
    case dessert = "Dessert"
    case snack = "Snack"
    case drink = "Drink"
}

struct Recipe:Identifiable {
    let id = UUID()
    let name:String
    let description:String
    let image:String
    let ingredients:String
    let directions:String
    let category:Category.RawValue
    let datePublished:String
    let url:String
}

extension Recipe {
    
    static let all = [
        Recipe(name: "Carrot Dogs", description: "Orange you glad we rounded up our favorite carrot recipes just in time for spring? Colorful, sweet, affordable, and versatile, the carrot is a stalwart of the healthy plant-based kitchen. With its sweet, easy flavor, carrot can rock out as a star ingredient or a supporting player, whether eaten cooked or raw; added to stir-fries, salads, soups, stews, sushi, dressings, cakes, oatmeal, or hummus; or even turned into vegan hot dogs. No vegan fridge is complete without a bag of carrots in it!", image: "https://www.forksoverknives.com/wp-content/uploads/fly-images/119698/Carrot-Dogs-for-Wordpress-1-scaled-688x387-c.jpg", ingredients: "8 large carrots 1 cup low-sodium vegetable broth ¼ cup apple cider vinegar               2 tablespoons reduced-sodium soy sauce or tamari2 tablespoons pure maple syrup2 teaspoons smoked paprika2 teaspoons dry mustard½ teaspoon ground coriander½ teaspoon garlic powder½ teaspoon onion powder½ teaspoon liquid smokeDash ground cloves8 whole wheat hot dog buns, toasted if desired½ of a red onion, finely chopped (¼ cup)3 tablespoons stone-ground mustard ½ of a medium cucumber, spiralized", directions: "Peel carrots and trim to 6 inches long. Trim wide end to make a consistent thickness. Place carrots in a large saucepan; add water to cover. Cover pan and bring to boiling; reduce heat to low. Cook carrots 8 to 10 minutes, until just tender. Drain well. Place carrots in a large resealable plastic bag set in a shallow dish. For marinade, in a bowl combine the next 11 ingredients (through cloves) and ½ cup water. Pour over carrots; seal bag. Chill 4 to 24 hours, turning occasionally. Drain and discard marinade. Grill carrots, covered, over medium-high 5 to 8 minutes or until grill marks start to appear, turning occasionally. Or place carrots in a foil-lined baking pan and bake at 450°F 8 to 10 minutes or until lightly browned on edges. Place grilled carrots in buns. Top with red onion, mustard, and cucumber.", category: "Main", datePublished: "2021-11-11", url:"https://www.forksoverknives.com/recipes/vegan-burgers-wraps/carrot-dogs/"),
        Recipe(name: "Hot Dogs", description: "Orange you glad we rounded up our favorite carrot recipes just in time for spring? Colorful, sweet, affordable, and versatile, the carrot is a stalwart of the healthy plant-based kitchen. With its sweet, easy flavor, carrot can rock out as a star ingredient or a supporting player, whether eaten cooked or raw; added to stir-fries, salads, soups, stews, sushi, dressings, cakes, oatmeal, or hummus; or even turned into vegan hot dogs. No vegan fridge is complete without a bag of carrots in it!", image: "https://www.forksoverknives.com/wp-content/uploads/fly-images/119698/Carrot-Dogs-for-Wordpress-1-scaled-688x387-c.jpg", ingredients: "8 large carrots 1 cup low-sodium vegetable broth ¼ cup apple cider vinegar               2 tablespoons reduced-sodium soy sauce or tamari2 tablespoons pure maple syrup2 teaspoons smoked paprika2 teaspoons dry mustard½ teaspoon ground coriander½ teaspoon garlic powder½ teaspoon onion powder½ teaspoon liquid smokeDash ground cloves8 whole wheat hot dog buns, toasted if desired½ of a red onion, finely chopped (¼ cup)3 tablespoons stone-ground mustard ½ of a medium cucumber, spiralized", directions: "Peel carrots and trim to 6 inches long. Trim wide end to make a consistent thickness. Place carrots in a large saucepan; add water to cover. Cover pan and bring to boiling; reduce heat to low. Cook carrots 8 to 10 minutes, until just tender. Drain well. Place carrots in a large resealable plastic bag set in a shallow dish. For marinade, in a bowl combine the next 11 ingredients (through cloves) and ½ cup water. Pour over carrots; seal bag. Chill 4 to 24 hours, turning occasionally. Drain and discard marinade. Grill carrots, covered, over medium-high 5 to 8 minutes or until grill marks start to appear, turning occasionally. Or place carrots in a foil-lined baking pan and bake at 450°F 8 to 10 minutes or until lightly browned on edges. Place grilled carrots in buns. Top with red onion, mustard, and cucumber.", category: "Main", datePublished: "2021-11-11", url:"https://www.forksoverknives.com/recipes/vegan-burgers-wraps/carrot-dogs/"),
        Recipe(name: "Vegetable Soup", description: "Orange you glad we rounded up our favorite carrot recipes just in time for spring? Colorful, sweet, affordable, and versatile, the carrot is a stalwart of the healthy plant-based kitchen. With its sweet, easy flavor, carrot can rock out as a star ingredient or a supporting player, whether eaten cooked or raw; added to stir-fries, salads, soups, stews, sushi, dressings, cakes, oatmeal, or hummus; or even turned into vegan hot dogs. No vegan fridge is complete without a bag of carrots in it!", image: "https://www.forksoverknives.com/wp-content/uploads/fly-images/119698/Carrot-Dogs-for-Wordpress-1-scaled-688x387-c.jpg", ingredients: "8 large carrots 1 cup low-sodium vegetable broth ¼ cup apple cider vinegar               2 tablespoons reduced-sodium soy sauce or tamari2 tablespoons pure maple syrup2 teaspoons smoked paprika2 teaspoons dry mustard½ teaspoon ground coriander½ teaspoon garlic powder½ teaspoon onion powder½ teaspoon liquid smokeDash ground cloves8 whole wheat hot dog buns, toasted if desired½ of a red onion, finely chopped (¼ cup)3 tablespoons stone-ground mustard ½ of a medium cucumber, spiralized", directions: "Peel carrots and trim to 6 inches long. Trim wide end to make a consistent thickness. Place carrots in a large saucepan; add water to cover. Cover pan and bring to boiling; reduce heat to low. Cook carrots 8 to 10 minutes, until just tender. Drain well. Place carrots in a large resealable plastic bag set in a shallow dish. For marinade, in a bowl combine the next 11 ingredients (through cloves) and ½ cup water. Pour over carrots; seal bag. Chill 4 to 24 hours, turning occasionally. Drain and discard marinade. Grill carrots, covered, over medium-high 5 to 8 minutes or until grill marks start to appear, turning occasionally. Or place carrots in a foil-lined baking pan and bake at 450°F 8 to 10 minutes or until lightly browned on edges. Place grilled carrots in buns. Top with red onion, mustard, and cucumber.", category: "Main", datePublished: "2021-11-11", url:"https://www.forksoverknives.com/recipes/vegan-burgers-wraps/carrot-dogs/"),
        Recipe(name: "Meat Soup", description: "Orange you glad we rounded up our favorite carrot recipes just in time for spring? Colorful, sweet, affordable, and versatile, the carrot is a stalwart of the healthy plant-based kitchen. With its sweet, easy flavor, carrot can rock out as a star ingredient or a supporting player, whether eaten cooked or raw; added to stir-fries, salads, soups, stews, sushi, dressings, cakes, oatmeal, or hummus; or even turned into vegan hot dogs. No vegan fridge is complete without a bag of carrots in it!", image: "https://www.forksoverknives.com/wp-content/uploads/fly-images/119698/Carrot-Dogs-for-Wordpress-1-scaled-688x387-c.jpg", ingredients: "8 large carrots 1 cup low-sodium vegetable broth ¼ cup apple cider vinegar               2 tablespoons reduced-sodium soy sauce or tamari2 tablespoons pure maple syrup2 teaspoons smoked paprika2 teaspoons dry mustard½ teaspoon ground coriander½ teaspoon garlic powder½ teaspoon onion powder½ teaspoon liquid smokeDash ground cloves8 whole wheat hot dog buns, toasted if desired½ of a red onion, finely chopped (¼ cup)3 tablespoons stone-ground mustard ½ of a medium cucumber, spiralized", directions: "Peel carrots and trim to 6 inches long. Trim wide end to make a consistent thickness. Place carrots in a large saucepan; add water to cover. Cover pan and bring to boiling; reduce heat to low. Cook carrots 8 to 10 minutes, until just tender. Drain well. Place carrots in a large resealable plastic bag set in a shallow dish. For marinade, in a bowl combine the next 11 ingredients (through cloves) and ½ cup water. Pour over carrots; seal bag. Chill 4 to 24 hours, turning occasionally. Drain and discard marinade. Grill carrots, covered, over medium-high 5 to 8 minutes or until grill marks start to appear, turning occasionally. Or place carrots in a foil-lined baking pan and bake at 450°F 8 to 10 minutes or until lightly browned on edges. Place grilled carrots in buns. Top with red onion, mustard, and cucumber.", category: "Main", datePublished: "2021-11-11", url:"https://www.forksoverknives.com/recipes/vegan-burgers-wraps/carrot-dogs/"),
        Recipe(name: "Tomato Soup", description: "Orange you glad we rounded up our favorite carrot recipes just in time for spring? Colorful, sweet, affordable, and versatile, the carrot is a stalwart of the healthy plant-based kitchen. With its sweet, easy flavor, carrot can rock out as a star ingredient or a supporting player, whether eaten cooked or raw; added to stir-fries, salads, soups, stews, sushi, dressings, cakes, oatmeal, or hummus; or even turned into vegan hot dogs. No vegan fridge is complete without a bag of carrots in it!", image: "https://www.forksoverknives.com/wp-content/uploads/fly-images/119698/Carrot-Dogs-for-Wordpress-1-scaled-688x387-c.jpg", ingredients: "8 large carrots 1 cup low-sodium vegetable broth ¼ cup apple cider vinegar               2 tablespoons reduced-sodium soy sauce or tamari2 tablespoons pure maple syrup2 teaspoons smoked paprika2 teaspoons dry mustard½ teaspoon ground coriander½ teaspoon garlic powder½ teaspoon onion powder½ teaspoon liquid smokeDash ground cloves8 whole wheat hot dog buns, toasted if desired½ of a red onion, finely chopped (¼ cup)3 tablespoons stone-ground mustard ½ of a medium cucumber, spiralized", directions: "Peel carrots and trim to 6 inches long. Trim wide end to make a consistent thickness. Place carrots in a large saucepan; add water to cover. Cover pan and bring to boiling; reduce heat to low. Cook carrots 8 to 10 minutes, until just tender. Drain well. Place carrots in a large resealable plastic bag set in a shallow dish. For marinade, in a bowl combine the next 11 ingredients (through cloves) and ½ cup water. Pour over carrots; seal bag. Chill 4 to 24 hours, turning occasionally. Drain and discard marinade. Grill carrots, covered, over medium-high 5 to 8 minutes or until grill marks start to appear, turning occasionally. Or place carrots in a foil-lined baking pan and bake at 450°F 8 to 10 minutes or until lightly browned on edges. Place grilled carrots in buns. Top with red onion, mustard, and cucumber.", category: "Main", datePublished: "2021-11-11", url:"https://www.forksoverknives.com/recipes/vegan-burgers-wraps/carrot-dogs/"),
        Recipe(name: "Cabbage Soup", description: "Orange you glad we rounded up our favorite carrot recipes just in time for spring? Colorful, sweet, affordable, and versatile, the carrot is a stalwart of the healthy plant-based kitchen. With its sweet, easy flavor, carrot can rock out as a star ingredient or a supporting player, whether eaten cooked or raw; added to stir-fries, salads, soups, stews, sushi, dressings, cakes, oatmeal, or hummus; or even turned into vegan hot dogs. No vegan fridge is complete without a bag of carrots in it!", image: "https://www.forksoverknives.com/wp-content/uploads/fly-images/119698/Carrot-Dogs-for-Wordpress-1-scaled-688x387-c.jpg", ingredients: "8 large carrots 1 cup low-sodium vegetable broth ¼ cup apple cider vinegar               2 tablespoons reduced-sodium soy sauce or tamari2 tablespoons pure maple syrup2 teaspoons smoked paprika2 teaspoons dry mustard½ teaspoon ground coriander½ teaspoon garlic powder½ teaspoon onion powder½ teaspoon liquid smokeDash ground cloves8 whole wheat hot dog buns, toasted if desired½ of a red onion, finely chopped (¼ cup)3 tablespoons stone-ground mustard ½ of a medium cucumber, spiralized", directions: "Peel carrots and trim to 6 inches long. Trim wide end to make a consistent thickness. Place carrots in a large saucepan; add water to cover. Cover pan and bring to boiling; reduce heat to low. Cook carrots 8 to 10 minutes, until just tender. Drain well. Place carrots in a large resealable plastic bag set in a shallow dish. For marinade, in a bowl combine the next 11 ingredients (through cloves) and ½ cup water. Pour over carrots; seal bag. Chill 4 to 24 hours, turning occasionally. Drain and discard marinade. Grill carrots, covered, over medium-high 5 to 8 minutes or until grill marks start to appear, turning occasionally. Or place carrots in a foil-lined baking pan and bake at 450°F 8 to 10 minutes or until lightly browned on edges. Place grilled carrots in buns. Top with red onion, mustard, and cucumber.", category: "Main", datePublished: "2021-11-11", url:"https://www.forksoverknives.com/recipes/vegan-burgers-wraps/carrot-dogs/")
    
    
    
    ]

}
